FROM ubuntu:18.04

MAINTAINER Jawon Song <jawon@tacc.utexas.edu>
MAINTAINER Amanda Cooksey <amcooksey@arizona.edu>
MAINTAINER Surya Saha <suryasaha@arizona.edu>
LABEL conda install

RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get install -y \
        parallel        \
        openjdk-11-jre  \
        build-essential \
        pkg-config      \
        bzip2           \
        libdw1          \
        nano            \
	wget		\
	git		\
	perl		\
	python3		\
        ca-certificates && \
    apt-get clean && \
    apt-get purge && \
    rm -rf /var/lib/apt/lists/* /tmp/*

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh


RUN conda config --add channels bioconda

RUN conda upgrade conda

RUN conda install -c conda-forge -c bioconda interproscan==5.54-87 

RUN chmod 777 /root/miniconda3/share/InterProScan/interproscan.sh /root/miniconda3/bin/interproscan.sh

ADD splitfasta.pl /usr/bin
ADD iprs_wrapper.sh /usr/bin
ADD cyverse_parse_ips_xml.pl /usr/bin


ENTRYPOINT ["/bin/bash", "iprs_wrapper.sh"]
##################### INSTALLATION END #####################
